version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=smartedx-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: >
      bash -c "python smartedx/manage.py makemigrations core &&
               python smartedx/manage.py migrate &&
               python smartedx/manage.py createsuperuser --noinput &&
               rm -rf smartedx/staticfiles &&
               python smartedx/manage.py collectstatic --noinput &&
               python smartedx/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=please_change_me
      - POSTGRES_NAME=smartedx-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - USE_S3=TRUE
      - AWS_S3_ACCESS_KEY_ID=please_change_me
      - AWS_S3_SECRET_ACCESS_KEY=please_change_me
      - AWS_S3_REGION_NAME=please_change_me
      - AWS_STORAGE_BUCKET_NAME=please_change_me
      - AWS_S3_ADDRESSING_STYLE=virtual
    depends_on:
      - db
    links:
      - db:db