version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=electoz
  web:
    build: .
    command: >
      bash -c "# python smartedx/manage.py makemigrations &&
               python smartedx/manage.py migrate &&
               python smartedx/manage.py makemigrations dashboard &&
               python smartedx/manage.py migrate &&
               python smartedx/manage.py createsuperuser --noinput &&
               python smartedx/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=electoz
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    depends_on:
      - db
    links:
      - db:db