# Generated by Django 5.0.7 on 2024-07-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitemassignment',
            name='name',
            field=models.CharField(default='title 1', max_length=255),
            preserve_default=False,
        ),
    ]
