# Generated by Django 5.0.6 on 2024-06-17 22:58

import dashboard.models.batch
import dashboard.models.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('established', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), dashboard.models.utils.max_value_current_year])),
            ],
            options={
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='dashboard.department')),
            ],
            options={
                'verbose_name_plural': 'programmes',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2024)])),
                ('graduation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2034)])),
                ('semester', models.CharField(choices=dashboard.models.batch.get_sems, default='1', max_length=1)),
                ('has_graduated', models.BooleanField(default=False)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='dashboard.programme')),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('only_one', models.BooleanField(default=False)),
                ('one_per_dept', models.BooleanField(default=False)),
                ('only_for_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.department')),
            ],
            options={
                'verbose_name_plural': 'staff roles',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='dashboard.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='dashboard.staffrole')),
            ],
            options={
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='dashboard.batch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('programme', 'admission_year', 'graduation_year', 'semester'), name='dashboard_batch_unique'),
        ),
    ]
